import { Routes, Route, Link, useParams, useNavigate } from 'react-router-dom';
import { useState, useEffect } from 'react';
import ReactMarkdown from 'react-markdown';
import remarkGfm from 'remark-gfm';

// The data is generated by the build script and placed in public/data.json
interface Monograph {
  id: string;
  title: string;
  category: string;
  content: string;
  imageUrl?: string | null;
}

function Dashboard({ data }: { data: Monograph[] }) {
  const [search, setSearch] = useState('');
  const [expandedCategory, setExpandedCategory] = useState<string | null>(null);
  
  const categories = Array.from(new Set(data.map(d => d.category))).sort();

  const filteredData = data.filter(d => 
    d.title.toLowerCase().includes(search.toLowerCase()) || 
    d.category.toLowerCase().includes(search.toLowerCase())
  );

  return (
    <div className="dashboard-container animate-fade-in">
      <header className="hero">
        <h1 className="gradient-text">Spiral Wiki</h1>
        <p className="subtitle">Das kybernetische Lexikon der Spiral Mindlaxy, der grafischen Oberfläche, der UI des ADHS OS</p>
        <div className="search-bar">
          <input 
            type="text" 
            placeholder="Suche nach Denkern oder Disziplinen..." 
            value={search}
            onChange={e => setSearch(e.target.value)}
          />
        </div>
      </header>

      <div className="stats-container">
        <div className="stat-box glass">
          <h3>Einträge</h3>
          <p className="stat-number">{data.length}</p>
        </div>
        <div className="stat-box glass">
          <h3>Kategorien</h3>
          <p className="stat-number">{categories.length}</p>
        </div>
      </div>

      <div className="category-grid">
        {categories.map(category => {
          const categoryItems = filteredData.filter(d => d.category === category);
          if (categoryItems.length === 0) return null;
          
          const isExpanded = expandedCategory === category || search.length > 0;
          
          return (
            <div 
              key={category} 
              className={`category-card glass ${isExpanded ? 'expanded' : ''}`}
            >
              <h2 
                className="category-title" 
                onClick={() => setExpandedCategory(isExpanded && search.length === 0 ? null : category)}
                style={{ cursor: 'pointer', display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}
              >
                {category}
                <span style={{ fontSize: '0.8em', opacity: 0.5 }}>{isExpanded ? '▼' : '▶'}</span>
              </h2>
              
              {isExpanded && (
                <ul className="monograph-list animate-slide-up">
                  {categoryItems.map(item => (
                    <li key={item.id}>
                      <Link to={`/monograph/${item.id}`} className="monograph-link">
                        {item.imageUrl && (
                          <div className="monograph-avatar" style={{ backgroundImage: `url(${item.imageUrl})` }}></div>
                        )}
                        <span>{item.title}</span>
                      </Link>
                    </li>
                  ))}
                </ul>
              )}
            </div>
          );
        })}
      </div>
    </div>
  );
}

function MonographReader({ data }: { data: Monograph[] }) {
  const { id } = useParams<{ id: string }>();
  const navigate = useNavigate();
  const monograph = data.find(d => d.id === id);

  if (!monograph) {
    return (
      <div className="reader-container not-found glass">
        <h2>Monographie nicht gefunden</h2>
        <button className="btn-primary" onClick={() => navigate('/')}>Zurück zur Bibliothek</button>
      </div>
    );
  }


  return (
    <div className="reader-wrapper animate-slide-up">
      <nav className="reader-nav glass">
        <button className="btn-back" onClick={() => navigate('/')}>
          <span className="icon">←</span> Zurück
        </button>
        <span className="category-badge">{monograph.category}</span>
      </nav>
      
      <article className="reader-content glass">
        <ReactMarkdown remarkPlugins={[remarkGfm]}>
          {monograph.content}
        </ReactMarkdown>
      </article>
    </div>
  );
}

export default function App() {
  const [data, setData] = useState<Monograph[]>([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    fetch('/data.json')
      .then(res => res.json())
      .then(json => {
        setData(json);
        setLoading(false);
      })
      .catch(err => {
        console.error("Failed to load wiki data", err);
        setLoading(false);
      });
  }, []);

  if (loading) {
    return <div className="loader-container"><div className="spinner"></div><p>Lade Spiral Wiki...</p></div>;
  }

  return (
    <div className="app-layout">
      <Routes>
        <Route path="/" element={<Dashboard data={data} />} />
        <Route path="/monograph/:id" element={<MonographReader data={data} />} />
      </Routes>
    </div>
  );
}
