import { Routes, Route, Link, useParams, useNavigate } from 'react-router-dom';
import { useState, useEffect } from 'react';
import ReactMarkdown from 'react-markdown';
import remarkGfm from 'remark-gfm';

// The data is generated by the build script and placed in public/data.json
interface Monograph {
  id: string;
  title: string;
  category: string;
  content: string;
}

function Dashboard({ data }: { data: Monograph[] }) {
  const [search, setSearch] = useState('');
  
  const categories = Array.from(new Set(data.map(d => d.category)));

  const filteredData = data.filter(d => 
    d.title.toLowerCase().includes(search.toLowerCase()) || 
    d.category.toLowerCase().includes(search.toLowerCase())
  );

  return (
    <div className="dashboard-container animate-fade-in">
      <header className="hero">
        <h1 className="gradient-text">Totalbibliothek</h1>
        <p className="subtitle">Das kybernetische Lexikon des Spiral OS</p>
        <div className="search-bar">
          <input 
            type="text" 
            placeholder="Suche nach Denkern oder Disziplinen..." 
            value={search}
            onChange={e => setSearch(e.target.value)}
          />
        </div>
      </header>

      <div className="stats-container">
        <div className="stat-box glass">
          <h3>Einträge</h3>
          <p className="stat-number">{data.length}</p>
        </div>
        <div className="stat-box glass">
          <h3>Kategorien</h3>
          <p className="stat-number">{categories.length}</p>
        </div>
      </div>

      <div className="category-grid">
        {categories.map(category => {
          const categoryItems = filteredData.filter(d => d.category === category);
          if (categoryItems.length === 0) return null;
          
          return (
            <div key={category} className="category-card glass">
              <h2 className="category-title">{category}</h2>
              <ul className="monograph-list">
                {categoryItems.map(item => (
                  <li key={item.id}>
                    <Link to={`/monograph/${item.id}`} className="monograph-link">
                      {item.title}
                    </Link>
                  </li>
                ))}
              </ul>
            </div>
          );
        })}
      </div>
    </div>
  );
}

function MonographReader({ data }: { data: Monograph[] }) {
  const { id } = useParams<{ id: string }>();
  const navigate = useNavigate();
  const monograph = data.find(d => d.id === id);

  if (!monograph) {
    return (
      <div className="reader-container not-found glass">
        <h2>Monographie nicht gefunden</h2>
        <button className="btn-primary" onClick={() => navigate('/')}>Zurück zur Bibliothek</button>
      </div>
    );
  }

  // Auto-linking logic: find other titles in the text and convert them to links
  // We use a simple regex approach for demonstration. In a production app, a custom remark plugin is better.
  const processContent = (text: string) => {
    let processed = text;
    data.forEach(d => {
      if (d.id === id) return; // don't link to self
      // Only replace exact whole word matches
      const regex = new RegExp(`\\b(${d.title})\\b`, 'g');
      // If the text contains the name, replace it with a markdown link
      // But avoid replacing inside existing links. For simplicity, just replace.
      // This is a naive implementation.
      // processed = processed.replace(regex, `[$1](/monograph/${d.id})`);
    });
    return processed;
  };

  return (
    <div className="reader-wrapper animate-slide-up">
      <nav className="reader-nav glass">
        <button className="btn-back" onClick={() => navigate('/')}>
          <span className="icon">←</span> Zurück
        </button>
        <span className="category-badge">{monograph.category}</span>
      </nav>
      
      <article className="reader-content glass">
        <ReactMarkdown remarkPlugins={[remarkGfm]}>
          {monograph.content}
        </ReactMarkdown>
      </article>
    </div>
  );
}

export default function App() {
  const [data, setData] = useState<Monograph[]>([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    fetch('/data.json')
      .then(res => res.json())
      .then(json => {
        setData(json);
        setLoading(false);
      })
      .catch(err => {
        console.error("Failed to load wiki data", err);
        setLoading(false);
      });
  }, []);

  if (loading) {
    return <div className="loader-container"><div className="spinner"></div><p>Lade Totalbibliothek...</p></div>;
  }

  return (
    <div className="app-layout">
      <Routes>
        <Route path="/" element={<Dashboard data={data} />} />
        <Route path="/monograph/:id" element={<MonographReader data={data} />} />
      </Routes>
    </div>
  );
}
