import { Routes, Route, Link, useParams, useNavigate } from 'react-router-dom';
import { useState, useEffect } from 'react';
import ReactMarkdown from 'react-markdown';
import remarkGfm from 'remark-gfm';

// Custom Hook für lokalen Speicher
function useLocalStorage<T>(key: string, initialValue: T): [T, (value: T | ((val: T) => T)) => void] {
  const [storedValue, setStoredValue] = useState<T>(() => {
    try {
      const item = window.localStorage.getItem(key);
      return item ? JSON.parse(item) : initialValue;
    } catch (error) {
      console.warn(error);
      return initialValue;
    }
  });

  const setValue = (value: T | ((val: T) => T)) => {
    try {
      const valueToStore = value instanceof Function ? value(storedValue) : value;
      setStoredValue(valueToStore);
      window.localStorage.setItem(key, JSON.stringify(valueToStore));
    } catch (error) {
      console.warn(error);
    }
  };
  return [storedValue, setValue];
}


// The data is generated by the build script and placed in public/data.json
interface Monograph {
  id: string;
  title: string;
  category: string;
  content: string;
  imageUrl?: string | null;
}

interface DashboardProps {
  data: Monograph[];
  readMonographs: string[];
}

function Dashboard({ data, readMonographs }: DashboardProps) {
  const [search, setSearch] = useState('');
  const [expandedCategory, setExpandedCategory] = useState<string | null>(null);
  
  const categories = Array.from(new Set(data.map(d => d.category))).sort();

  const filteredData = data.filter(d => 
    d.title.toLowerCase().includes(search.toLowerCase()) || 
    d.category.toLowerCase().includes(search.toLowerCase())
  );

  return (
    <div className="dashboard-container animate-fade-in">
      <header className="hero">
        <h1 className="gradient-text">SPiRAL MiND WiKi</h1>
        <p className="subtitle">Das kybernetische Lexikon der Spiral Mindlaxy, der grafischen Oberfläche, der UI des ADHS OS</p>
        <div className="search-bar">
          <input 
            type="text" 
            placeholder="Suche nach Denkern oder Disziplinen..." 
            value={search}
            onChange={e => setSearch(e.target.value)}
          />
        </div>
      </header>

      <div className="stats-container">
        <div className="stat-box glass">
          <h3>Einträge</h3>
          <p className="stat-number">{data.length}</p>
        </div>
        <div className="stat-box glass">
          <h3>Kategorien</h3>
          <p className="stat-number">{categories.length}</p>
        </div>
        <div className="stat-box glass highlight-box">
          <h3>Erforscht</h3>
          <p className="stat-number">{readMonographs.length}</p>
          <div className="progress-bar-container">
            <div className="progress-bar-fill" style={{ width: `${Math.round((readMonographs.length / data.length) * 100)}%` }}></div>
          </div>
          <p className="progress-text">{Math.round((readMonographs.length / data.length) * 100)}% gesamt</p>
        </div>
      </div>

      <div className="category-grid">
        {categories.map(category => {
          const categoryItems = filteredData.filter(d => d.category === category);
          if (categoryItems.length === 0) return null;
          
          const isExpanded = expandedCategory === category || search.length > 0;
          const categoryReadCount = categoryItems.filter(item => readMonographs.includes(item.id)).length;
          const catProgress = Math.round((categoryReadCount / categoryItems.length) * 100);
          
          return (
            <div 
              key={category} 
              className={`category-card glass ${isExpanded ? 'expanded' : ''}`}
            >
              <div 
                className="category-header"
                onClick={() => setExpandedCategory(isExpanded && search.length === 0 ? null : category)}
              >
                <div className="category-title-row">
                  <h2 className="category-title">{category}</h2>
                  <span className="expand-icon">{isExpanded ? '▼' : '▶'}</span>
                </div>
                <div className="category-progress-container">
                  <div className="category-progress-text">
                    {categoryReadCount} von {categoryItems.length} erkundet ({catProgress}%)
                  </div>
                  <div className="progress-bar-container small">
                    <div className="progress-bar-fill" style={{ width: `${catProgress}%` }}></div>
                  </div>
                </div>
              </div>
              
              {isExpanded && (
                <ul className="monograph-list animate-slide-up">
                  {categoryItems.map(item => {
                    const isRead = readMonographs.includes(item.id);
                    return (
                      <li key={item.id}>
                        <Link to={`/monograph/${item.id}`} className={`monograph-link ${isRead ? 'read' : ''}`}>
                          {item.imageUrl && (
                            <div className="monograph-avatar-wrapper">
                              <img src={item.imageUrl} alt={item.title} className="monograph-avatar-img" loading="lazy" />
                              {isRead && <div className="read-badge">✓</div>}
                            </div>
                          )}
                          {!item.imageUrl && isRead && <span className="read-badge-text">✓</span>}
                          <span>{item.title}</span>
                        </Link>
                      </li>
                    );
                  })}
                </ul>
              )}
            </div>
          );
        })}
      </div>
    </div>
  );
}

interface ReaderProps {
  data: Monograph[];
  markAsRead: (id: string) => void;
}

function MonographReader({ data, markAsRead }: ReaderProps) {
  const { id } = useParams<{ id: string }>();
  const navigate = useNavigate();
  const monograph = data.find(d => d.id === id);

  useEffect(() => {
    if (id && monograph) {
      markAsRead(id);
    }
  }, [id, monograph, markAsRead]);

  if (!monograph) {
    return (
      <div className="reader-container not-found glass">
        <h2>Monographie nicht gefunden</h2>
        <button className="btn-primary" onClick={() => navigate('/')}>Zurück zur Bibliothek</button>
      </div>
    );
  }


  return (
    <div className="reader-wrapper animate-slide-up">
      <nav className="reader-nav glass">
        <button className="btn-back" onClick={() => navigate('/')}>
          <span className="icon">←</span> Zurück
        </button>
        <span className="category-badge">{monograph.category}</span>
      </nav>
      
      <article className="reader-content glass">
        <ReactMarkdown 
          remarkPlugins={[remarkGfm]}
          components={{
            a: ({node, ...props}) => {
              const href = props.href || '';
              // Interne Links via React Router leiten
              if (href.startsWith('/monograph/')) {
                return <Link to={href} className="wiki-link">{props.children}</Link>;
              }
              // Externe Links klassisch öffnen
              return <a target="_blank" rel="noopener noreferrer" className="external-link" {...props}>{props.children}</a>;
            }
          }}
        >
          {monograph.content}
        </ReactMarkdown>
      </article>
    </div>
  );
}

export default function App() {
  const [data, setData] = useState<Monograph[]>([]);
  const [loading, setLoading] = useState(true);
  const [readMonographs, setReadMonographs] = useLocalStorage<string[]>('spiral-wiki-read', []);

  const markAsRead = (id: string) => {
    setReadMonographs(prev => {
      if (!prev.includes(id)) {
        return [...prev, id];
      }
      return prev;
    });
  };

  useEffect(() => {
    fetch('/data.json')
      .then(res => res.json())
      .then(json => {
        setData(json);
        setLoading(false);
      })
      .catch(err => {
        console.error("Failed to load wiki data", err);
        setLoading(false);
      });
  }, []);

  if (loading) {
    return <div className="loader-container"><div className="spinner"></div><p>Lade Spiral Wiki...</p></div>;
  }

  return (
    <div className="app-layout">
      <Routes>
        <Route path="/" element={<Dashboard data={data} readMonographs={readMonographs} />} />
        <Route path="/monograph/:id" element={<MonographReader data={data} markAsRead={markAsRead} />} />
      </Routes>
    </div>
  );
}
